Nest auth
MukdamDev/mukdam-platform pull request #6
Opened 2022-11-27 01:19 UTC by YuraOkolodko

2022-11-27 06:01 UTC, erikash commented on app/.env.example
> +SECRET=secret
rename to JW_SECRET

2022-11-27 06:02 UTC, erikash commented on app/src/app.module.ts
> +  providers: [AppService, CustomersService],
You should probably register `CustomersService` as a provider in the `CustomersModule`

2022-11-27 06:03 UTC, erikash commented on app/src/auth/auth.module.ts
> +              signOptions: { expiresIn: '60s' },
60 seconds really is the best practice?

2022-11-27 06:04 UTC, erikash commented on app/src/auth/auth.module.ts
> +      ConfigService
You probably don't need to register `ConfigService` as a provider, you can import `ConfigModule` instead.

2022-11-27 06:06 UTC, erikash commented on app/src/auth/auth.service.ts
> +    async login(user: any) {
Why `any`?

2022-11-27 06:08 UTC, erikash commented on app/src/auth/strategies/headerapikey.strategy.ts
> +        if (this.configService.get<string>('API_KEY') === apiKey) {
Could you promisify the callback?

2022-11-27 06:11 UTC, erikash commented on app/src/customers/customers.controller.ts
> +    @UseGuards(HeaderapikeyAuthGuard)
Love it! ❤️

2022-11-27 06:12 UTC, erikash commented on app/src/customers/customers.module.ts
> +        ConfigService,
If you need `ConfigService` import the module don't include it in the providers

2022-11-27 06:12 UTC, erikash commented on app/src/customers/customers.module.ts
> +        HeaderApiKeyStrategy,
Same here - import from `AuthModule`

2022-11-27 06:12 UTC, erikash commented on app/src/index.ts
> +  console.log('HANDLER HERE');
Remove

2022-11-27 06:13 UTC, erikash commented on app/src/shared/infra/database/connectingString.ts
> +  if (!HOST || !PORT || !DB_NAME || !USERNAME || !PASSWORD || !SECRET) {
Remove SECRET reference

2022-11-27 06:13 UTC, erikash commented on app/src/shared/infra/database/connectingString.ts
> +    secret: SECRET,
Remove SECRET reference

2022-11-27 06:13 UTC, erikash commented on app/src/shared/infra/database/index.ts
> +  process.env["SECRET"] = secret;
Remove SECRET reference

2022-11-27 06:15 UTC, erikash commented on app/src/users/users.service.ts
> +                username: '+972528321351',
Love that the `phone` is the `username`

2022-11-27 06:16 UTC, erikash requested changes
Great job! very clean :)
See my minor changes requested...

2022-11-27 18:03 UTC, YuraOkolodko commented on app/src/auth/auth.module.ts
> +      ConfigService
Config service defined globally so no need import at all.

2022-11-27 18:03 UTC, YuraOkolodko commented on app/src/customers/customers.module.ts
> +        ConfigService,
Same as abowe ConfigService defined globally, no need to import.

2022-11-27 18:05 UTC, YuraOkolodko commented on app/src/customers/customers.module.ts
> +        HeaderApiKeyStrategy,
Yes config is global - no need to import

2022-11-27 18:51 UTC, erikash commented
My point was that you don’t need to define it as a provider in every module
:)

On Sun, 27 Nov 2022 at 20:05 Yura ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In app/src/customers/customers.module.ts
> <https://github.com/MukdamDev/mukdam-platform/pull/6#discussion_r1032987352>
> :
>
> > @@ -0,0 +1,13 @@
> +import { Module } from ***@***.***/common';
> +import { ConfigService } from ***@***.***/config";
> +import { CustomersService } from "./customers.service";
> +import { HeaderApiKeyStrategy } from "../auth/strategies/headerapikey.strategy";
> +
> ***@***.***({
> +    providers: [
> +        CustomersService,
> +        ConfigService,
> +        HeaderApiKeyStrategy,
>
> Yes config is global - no need to import
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MukdamDev/mukdam-platform/pull/6#discussion_r1032987352>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABCIPPMOVOBJPR6HFYQYO3WKOPGPANCNFSM6AAAAAASMIHREE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-11-28 06:15 UTC, erikash approved these changes
Look great!
Go ahead and merge :)

2022-11-28 09:44 UTC, merged